### ISSUE TITLE
Console debugging flow not working properly in Rescue People

### ISSUE THREAD

**Issue by espilya** [JdeRobot/RoboticsApplicationManager#158]
Issue from RA (https://github.com/JdeRobot/RoboticsAcademy/issues/2684)

**Comment by dduro2020** [comment]
The problem with the rescue people exercise is that it works differently, before executing the code, the drone is initialised, when the program fails in execution it cannot be paused and relaunched, the exercise has to be refreshed. I think we should separate it into two issues. In fact, it is very likely to be related to another issue. I think the `drone = DroneWrapper()` (in HAL.py) object may be causing problems when the program terminates due to a runtime error.

**Comment by dduro2020** [comment]
In fact, it is very likely to be related to another issue. I think the `drone = DroneWrapper()` (in HAL.py) object may be causing problems when the program terminates due to a runtime error.
